### ISSUE TITLE
There are two get requests for the same thing "all"

### ISSUE THREAD

**Issue by afituri** [AbdullahElamir/school#19]
![screen shot 2016-11-07 at 7 10 41 pm](https://cloud.githubusercontent.com/assets/1825624/20067472/f5bc2ee2-a51d-11e6-8d38-e40b8bd9c243.png)

also other thing what is this  ??????????: 
 var user={};
user.school="5801f550e4de0e349c8714c2";

This should be removed it is used for edit and other things

بالله يا شباب متخلوش حاجة جربتو بيها تقعد في الكود زي توا والله مشكلة كبيرة!!!!!!!!!!!!!!

**Comment by TahaAlmahmudi** [comment]
![image](https://cloud.githubusercontent.com/assets/12233585/20111983/12937428-a5f3-11e6-9d18-abb2c12167e5.png)
