### ISSUE TITLE
22# خطأ في هذه الصقحة بسبب استدعاء الدوال تحت بعض وليس داخل بعض وعدم تطبيق مفهوم الكلوجر جيدا 

### ISSUE THREAD

**Issue by AbdullahElamir** [AbdullahElamir/school#22]
![screenshot from 2016-11-07 19-44-49](https://cloud.githubusercontent.com/assets/10694513/20068792/aa15bb7a-a522-11e6-8064-f15b76d0ebf3.png)

**Comment by AbdullahElamir** [comment]
![screenshot from 2016-11-07 19-38-20](https://cloud.githubusercontent.com/assets/10694513/20068743/7a3aca26-a522-11e6-9a91-b2db4c4e229f.png)

**Comment by TahaAlmahmudi** [comment]
حدثت هذه المشكلة بسبب البيانات القديمة الموجودة في قاعدة البيانات لديك (والتي تم اضافتها سابقا بالهيكلية القديمة لقاعدة البيانات) ،،
هذه المشكلة تحدث دائما ويرجع السبب للتغيير الذي يحصل في هيكلية قاعدة البيانات بين كل فترة وفترة ،، فالبيانات القديمة المضافة مسبقاً هيكليتها غير مطابقة لهيكلية قاعدة البيانات الحالية والتي تعتمد عليها الخدمات الجديدة في المنظومة ،، وبالتالي يحدث هذا الخطأ ..
يمكن حل المشكلة بحذف جميع البيانات القديمة ومن ثم إضافة بيانات جديدة لكي تكون مطابقة لهيكلية قاعدة البيانات تماما ..
لقد تم إرسال في المجموعة في موقع slack بيانات قاعدة بيانات جديدة يمكنك عمل لها import وبالتالي سوف تحل المشكلة ..
ملاحظة : هذا الخطأ حدث سابقاً لكل من  @AbdullahElamir و @abdooageel في صفحة إضافة/تعديل نظام ،، بنفس الطريقة يمكنك عمل drop للداتا بيز و من ثم إضافة بيانات جديدة من المنظومة لتتحصل على بيانات مطابقة لهيكلية قاعدة البيانات ومنها تحل المشكلة ..
كما قلت لكم يرجع السبب للتغيير الذي يحصل في هيكلية قاعدة البيانات بين كل فترة وفترة وبالتالي نتحصل على بيانات هيكليتها قديمة مخزنة في قاعدة البيانات هيكليتها جديدة ..

**Comment by AbdullahElamir** [comment]
شكرا علي التوضيح طه @TahaAlmahmudi
