### ISSUE TITLE
add students to class room

### ISSUE THREAD

**Issue by abdorihan** [AbdullahElamir/school#31]

**Comment by abdorihan** [comment]
حاليا تضيف الطلبة القادمين دون النظر في الطلبة السابقين

**Comment by AbdullahElamir** [comment]
الرجاء ارفاق صورة من الصفحة او من رابط الصفحة التي حدث بها الخطأ مع التوضيح

**Comment by abdorihan** [comment]
![screenshot from 2016-11-12 16-38-02](https://cloud.githubusercontent.com/assets/13036155/20238531/7edfcbd0-a8f6-11e6-82a2-d412c9a17c37.png)

**Comment by abdorihan** [comment]
المشكلة قلت عليها لعبدالعظيم

**Comment by abdorihan** [comment]
المشكلة حصلت لوجود بيانات قديمة في الداتا بيز قبل اجراء عمليات الاعتمادية 
اي في واقع الامر لاتوجد مشكلة بعد تفعيل الاعتمادية قبل الحذف
