### ISSUE TITLE
#40عدم ظهور البوب اب  عند ادخال التاريخ للحقول التالية  - تاريخ الحصول عليه - تاريخ البدأ في العمل

### ISSUE THREAD

**Issue by AbdullahElamir** [AbdullahElamir/school#40]
#45عدم ظهور البوب اب  عند ادخال التاريخ للحقول التالية  - تاريخ الحصول عليه - تاريخ البدأ في العمل

**Comment by AbdullahElamir** [comment]
![screenshot from 2016-11-16 15-48-39](https://cloud.githubusercontent.com/assets/10694513/20349798/a283cc3c-ac14-11e6-9ce4-37053d5b4098.png)

**Comment by AbdullahElamir** [comment]
http://localhost:3000/admin#/newTeacher 

مكان الصفحة

**Comment by asonni** [comment]
I have fixed this issue see #41 Mr @AbdullahElamir

**Comment by AbdullahElamir** [comment]
Done !! QA by me
